Traceback (most recent call last):
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/site-packages/nbclient/client.py", line 782, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
    result = await obj
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/site-packages/jupyter_client/channels.py", line 313, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/site-packages/nbclient/client.py", line 1005, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/site-packages/nbclient/client.py", line 806, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/Users/hiroki_takikawa/.pyenv/versions/anaconda3-2022.10/envs/cssworkshop/lib/python3.9/site-packages/nbclient/client.py", line 856, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
["if not os.path.exists('scripts'):", "                os.makedirs('scripts')", '#このあたりにある', '#<div class="season"><h4>Season 1</h4><ul><li>1. <a href="/series/Suits-1632701/season-1/episode-1-Pilot" title=\'Transcript of episode 1 "Pilot"\'>Pilot</a></li><li>2', 'seasons = [item for item in soup.find_all(\'div\', class_="season")]']
...
['            script.decompose()#元のsoup_href()から指定されたオブジェクトを削除する', '        clean_text = scripts.get_text(separator="\\n")', "        with open(f'scripts/'+href.split('/')[4], 'w') as f:#hrefの5番目の/の後にエピソード名があるのでファイル名とする", '                f.write(clean_text)', '                print(f"Downloaded: " +href.split(\'/\')[4] +\'.txt\')']
-------------------

